### ISSUE TITLE
能不能默认小图替换高清大图？

### ISSUE THREAD

**Issue by aline2013** [WittBulter/readyLoadImg#1]
这个插件，只能针对滚固定宽高的图片，这样，default.png和真实图片一样大小，不是要准备2套图片？

**Comment by WittBulter** [comment]
是的，所以我默认准备了一个gulp的脚本，编译一套非常低质量的图片。
因为图片的地址并非CDN，前端不能够仅仅取得很低质量的图片，所以需要预先通过脚本编译出一套。不过如果仅仅只需要预加载新的图片，也是一个很好的想法，我会在重构一次，优化代码然后加入一些新的支持。
